<?php
function calc_engine($n)
{
	$pval=0;
	switch($n)
	{
		case 5:
			$pval=100000;
			break;
		case 4:
			$pval=75000;
			break;
		case 3:
			$pval=40000;
			break;
		case 2:
			$pval=20000;
			break;
		case 1:
			$pval=0;
			break;
	}
	return $pval;
}
function calc_ac($n)
{
	$pval=0;
	switch($n)
	{
		case 5:
			$pval=1000;
			break;
		case 4:
			$pval=75000;
			break;
		case 3:
			$pval=40000;
			break;
		case 2:
			$pval=20000;
			break;
		case 1:
			$pval=0;
			break;
	}
	return $pval;
}
function calc_starter($n)
{
	$pval=0;
	switch($n)
	{
		case 5:
			$pval=100000;
			break;
		case 4:
			$pval=75000;
			break;
		case 3:
			$pval=40000;
			break;
		case 2:
			$pval=20000;
			break;
		case 1:
			$pval=0;
			break;
	}
	return $pval;
}
function calc_radiator($n)
{
	$pval=0;
	switch($n)
	{
		case 5:
			$pval=100000;
			break;
		case 4:
			$pval=75000;
			break;
		case 3:
			$pval=40000;
			break;
		case 2:
			$pval=20000;
			break;
		case 1:
			$pval=0;
			break;
	}
	return $pval;
}
function calc_catalytic($n)
{
	$pval=0;
	switch($n)
	{
		case 5:
			$pval=100000;
			break;
		case 4:
			$pval=75000;
			break;
		case 3:
			$pval=40000;
			break;
		case 2:
			$pval=20000;
			break;
		case 1:
			$pval=0;
			break;
	}
	return $pval;
}
function calc_wheels($n)
{
	$pval=0;
	switch($n)
	{
		case 5:
			$pval=100000;
			break;
		case 4:
			$pval=75000;
			break;
		case 3:
			$pval=40000;
			break;
		case 2:
			$pval=20000;
			break;
		case 1:
			$pval=0;
			break;
	}
	return $pval;
}
function calc_battery($n)
{
	$pval=0;
	switch($n)
	{
		case 5:
			$pval=100000;
			break;
		case 4:
			$pval=75000;
			break;
		case 3:
			$pval=40000;
			break;
		case 2:
			$pval=20000;
			break;
		case 1:
			$pval=0;
			break;
	}
	return $pval;
}
function calc_seat($n)
{
	$pval=0;
	switch($n)
	{
		case 5:
			$pval=100000;
			break;
		case 4:
			$pval=75000;
			break;
		case 3:
			$pval=40000;
			break;
		case 2:
			$pval=20000;
			break;
		case 1:
			$pval=0;
			break;
	}
	return $pval;
}
function calc_horn($n)
{
	$pval=0;
	switch($n)
	{
		case 5:
			$pval=100000;
			break;
		case 4:
			$pval=75000;
			break;
		case 3:
			$pval=40000;
			break;
		case 2:
			$pval=20000;
			break;
		case 1:
			$pval=0;
			break;
	}
	return $pval;
}
function calc_body($n)
{
	$pval=0;
	switch($n)
	{
		case 5:
			$pval=100000;
			break;
		case 4:
			$pval=75000;
			break;
		case 3:
			$pval=40000;
			break;
		case 2:
			$pval=20000;
			break;
		case 1:
			$pval=0;
			break;
	}
	return $pval;
}

function calc($n)
{
	$pval=0;
	switch($n)
	{
		case 5:
			$pval=5000;
			break;
		case 4:
			$pval=4000;
			break;
		case 3:
			$pval=3000;
			break;
		case 2:
			$pval=2000;
			break;
		case 1:
			$pval=0;
			break;
	}
	return $pval;
}
?>